MBDesignWeb/Controllers/HRController.cs
using AspNetCore.Reporting;
using BusinessLogicMBDesign.Document;
using BusinessLogicMBDesign;
using BusinessLogicMBDesign.HR;
using BusinessLogicMBDesign.Master;
using DataLayerMBDesign;
using EntitiesMBDesign;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using UtilitiesMBDesign;
using NPOI.SS.UserModel;
using System;

namespace MBDesignWeb.Controllers
{
    public class HRController : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly HRService _hrService;
        private readonly EmployeeService _employeeService;
        public HRController(IConfiguration configuration)
        {
            _configuration = configuration;

            _hrService = new HRService(_configuration);
            _employeeService = new EmployeeService(_configuration);
        }

        public IActionResult Index()
        {
            ViewBag.apiUrl = _configuration.GetSection("apiUrl").Value;
            ViewBag.webUrl = _configuration.GetSection("webUrl").Value;
            ViewBag.imageUrl = _configuration.GetSection("imageUrl").Value;
            return View();
        }

        #region API
        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetLeaveTypeList(string leaveType, string status)
        {
            var data = _hrService.GetLeaveTypeList(leaveType, status);

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetSelect2LeaveTypeName()
        {
            var data = _hrService.GetSelect2LeaveTypeName();

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetLeaveTypeById(int leaveTypeId)
        {
            var data = _hrService.GetLeaveTypeById(leaveTypeId);

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpPost]
        public JsonResult UpdateLeaveType([FromBody] LeaveTypeModel obj)
        {
            var msg = _hrService.UpdateLeaveType(obj);

            return new JsonResult(msg);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetLeaveList(string empCode, string empName, string leaveType, string leaveStartDate, string leaveEndDate)
        {
            var data = _hrService.GetLeaveList(empCode, empName, leaveType, leaveStartDate, leaveEndDate);

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetLeaveById(int leaveId)
        {
            var data = _hrService.GetLeaveById(leaveId);

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetSelect2EmpCode(int empId = 0)
        {
            var data = _hrService.GetSelect2EmpCode(empId);

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetSelect2EmpFullName(int empId = 0)
        {
            var data = _hrService.GetSelect2EmpFullName(empId);

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpPost]
        public JsonResult AddLeave([FromBody] LeaveModel obj)
        {
            var msg = _hrService.AddLeave(obj);

            return new JsonResult(msg);
        }

        [Route("api/[controller]/[action]")]
        [HttpPost]
        public JsonResult UpdateLeave([FromBody] LeaveModel obj)
        {
            var msg = _hrService.UpdateLeave(obj);

            return new JsonResult(msg);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetLeaveSummaryByEmpData(string empCode, string empName)
        {
            var data = _hrService.GetLeaveSummaryByEmpData(empCode, empName);

            return new JsonResult(data);
        }


        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetOtherPaymentList(string empCode, string empName, string type, string installmentStartDate)
        {
            var data = _hrService.GetOtherPaymentList(empCode, empName, type, installmentStartDate);

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetOtherPaymentById(int otherPaymentId)
        {
            var data = _hrService.GetOtherPaymentById(otherPaymentId);

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpPost]
        public JsonResult AddOtherPaymentModel([FromBody]OtherPaymentModel obj)
        {
            var msg = _hrService.AddOtherPaymentModel(obj);

            return new JsonResult(msg);
        }


        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetAttendanceSettingList(string departmentId)
        {
            var msg = _hrService.GetAttendanceSettingList(departmentId);

            return new JsonResult(msg);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetAttendanceSettingById(int id)
        {
            var msg = _hrService.GetAttendanceSettingById(id);

            return new JsonResult(msg);
        }

        [Route("api/[controller]/[action]")]
        [HttpPost]
        public JsonResult AddAttendanceSetting([FromBody] AttendanceDepartmentSettingModel obj)
        {
            var msg = _hrService.AddAttendanceSetting(obj);

            return new JsonResult(msg);
        }

        [Route("api/[controller]/[action]")]
        [HttpPost]
        public JsonResult UpdateAttendanceSetting([FromBody] AttendanceDepartmentSettingModel obj)
        {
            var msg = _hrService.UpdateAttendanceSetting(obj);

            return new JsonResult(msg);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetAttendanceList(string empCode, string empName, string startDate, string endDate)
        {
            var msg = _hrService.GetAttendanceList(empCode, empName, startDate, endDate);

            return new JsonResult(msg);
        }


        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetSalaryList(string empCode, string empName, string startDate, string endDate)
        {
            var msg = _hrService.GetSalaryList(empCode, empName, startDate, endDate);

            return new JsonResult(msg);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetAttendanceSalaryList(string empCode, string empName, string leaveType, string startDate, string endDate)
        {
            var data = _hrService.GetAttendanceSalaryList(empCode, empName, leaveType, startDate, endDate);

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetAttendanceSalaryType()
        {
            var data = _hrService.GetAttendanceSalaryType();

            return new JsonResult(data);
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public JsonResult GetAttendanceOTList(string empCode, string empName, string startDate, string endDate)
        {
            var data = _hrService.GetAttendanceOTList(empCode, empName, startDate, endDate);

            return new JsonResult(data);
        }
        #endregion API

        [Route("api/[controller]/[action]")]
        [HttpPost]
        [DisableRequestSizeLimit]
        public ActionResult DoImportAttendance(string createBy, IFormFile formFile)
        {
            var msg = new ResultMessage();
            var addedUpload = new List<UploadFiles>();

            var ctxFile = HttpContext.Request.Form.Files;
            var retObject = new List<IDictionary<string, object>>();

            var added = new List<AttendanceView>();
            var newResult = new List<AttendanceView>();

            try
            {
                IWorkbook workbook = WorkbookFactory.Create(ctxFile[0].OpenReadStream());
                for (int i = 0; i < workbook.NumberOfSheets; i++)
                {
                    var worksheet = workbook.GetSheetAt(i);
                    var keys = new List<string>();
                    IRow keyRow = worksheet.GetRow(0);
                    if (keyRow != null)
                    {
                        for (int k = 0; k <= keyRow.LastCellNum; k++)
                        {
                            var cellData = keyRow.GetCell(k, MissingCellPolicy.RETURN_NULL_AND_BLANK);
                            var key = cellData != null ? cellData.StringCellValue : string.Empty;
                            //if (!string.IsNullOrEmpty(key))
                            keys.Add(key);
                        }
                    }

                    for (int j = 1; j <= worksheet.LastRowNum; j++)
                    {
                        var nullCount = 0;
                        IRow row = worksheet.GetRow(j);
                        if (row != null)
                        {
                            var dataRow = new Dictionary<string, object>();
                            for (int k = 0; k <= row.LastCellNum; k++)
                            {
                                var cellData = row.GetCell(k, MissingCellPolicy.RETURN_NULL_AND_BLANK);
                                var data = cellData != null ? cellData.ToString().Trim() : string.Empty;
                                dataRow.Add(keys.ElementAt(k), data);
                                if (string.IsNullOrEmpty(data))
                                    nullCount++;
                            }

                            if (nullCount < row.LastCellNum)
                                retObject.Add(dataRow);

MBDesignWeb/Controllers/LoginController.cs
using BusinessLogicMBDesign.Login;
using EntitiesMBDesign;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MBDesignWeb.Controllers
{
    public class LoginController : Controller
    {
		private readonly IConfiguration _configuration;
        private readonly LoginService _loginService;

        public LoginController(IConfiguration configuration)
		{
			_configuration = configuration;
            _loginService = new LoginService(configuration);
		}

		public IActionResult Index()
        {
			ViewBag.apiUrl = _configuration.GetSection("apiUrl").Value;
			ViewBag.webUrl = _configuration.GetSection("webUrl").Value;
            ViewBag.imageUrl = _configuration.GetSection("imageUrl").Value;
            return View();
        }

		[HttpPost]
		[AllowAnonymous]
		public IActionResult GoToMaster()
		{
            return RedirectToAction("Index", "Master");
        }

        [Route("api/[controller]/[action]")]
        [HttpGet]
        public IActionResult GetMenuPermissionPerEmpData(int id)
        {
            var result = _loginService.GetMenuPermissionPerEmpData(id);
            return Json(result);
        }

        [Route("api/[controller]/[action]")]
        [HttpPost]
        public IActionResult DoLogin([FromBody] LoginModel model)
        {
            var msg = new ResultMessage();

            var result = _loginService.GetEmpByUserAndPass(model.user, model.password);
            if (result != null)
            {
                msg.isResult = true;
                msg.strResult = "เข้าสู่ระบบสำเร็จ";
            }
            else
            {
                msg.isResult = false;
                msg.strResult = "ไม่พบช้อมูลพนักงานในระบบ";
            }

            var val = new
            {
                msg = msg,
                result = result
            };

            return Json(val);
        }
    }
}

MBDesignWeb/Controllers/SpecController.cs
using Microsoft.AspNetCore.Mvc;

namespace MBDesignWeb.Controllers
{
    public class SpecController : Controller
    {
        private readonly IConfiguration _configuration;

        public SpecController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            ViewBag.apiUrl = _configuration.GetSection("apiUrl").Value;
            ViewBag.webUrl = _configuration.GetSection("webUrl").Value;
            ViewBag.imageUrl = _configuration.GetSection("imageUrl").Value;
            return View();
        }
    }
}

MBDesignWeb/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;

namespace MBDesignWeb.Controllers
{
    public class StoreController : Controller
    {
        private readonly IConfiguration _configuration;

        public StoreController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            ViewBag.apiUrl = _configuration.GetSection("apiUrl").Value;
            ViewBag.webUrl = _configuration.GetSection("webUrl").Value;
            ViewBag.imageUrl = _configuration.GetSection("imageUrl").Value;
            return View();
        }
    }
}

MBDesignWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap-5.0.2-dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/MBDesignWeb.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/css/custom/style.css" />
    <link href="~/assets/fontawesome/css/all.min.css" rel="stylesheet">
    <script src="~/lib/jquery/dist/jquery.min.js" crossorigin="anonymous"></script>

    <script src="~/lib/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <link rel="stylesheet" href="~/assets/sweetalert/sweetalert2.min.css" />
    <script src="~/assets/sweetalert/sweetalert2.all.min.js"></script>

    <script src="~/scripts/config.js"></script>
    <script src="~/scripts/js-helper.js"></script>

    <script src="~/lib/axios/axios.min.js"></script>

    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

    <script src="~/lib/ajax/moment.min.js"></script>

    <script src="~/lib/lodash/lodash.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap-5.0.2-dist/base.css" />

    <link href="~/lib/loadingstyle.css" rel="stylesheet" />
    @*
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    *@
    <link href="~/lib/loadingstyle.css" rel="stylesheet" />
    <script>
        localStorage.setItem('webUrl', '@ViewBag.webUrl');
        localStorage.setItem('apiUrl', '@ViewBag.apiUrl');
        localStorage.setItem('imageUrl', '@ViewBag.imageUrl');
    </script>
    <script>
        let imageUrl = localStorage.getItem('imageUrl');
        let path = (imageUrl == "") ? ".." : imageUrl;
        function onmouseoverAction(x,name) {
            $(`#${x}`).removeAttr("src");
            $(`#${x}`).attr('src', `${path}/images/${name}_2.png`);
        }
        function onmouseoutAction(x,name) {
            $(`#${x}`).removeAttr("src");
            $(`#${x}`).attr('src', `${path}/images/${name}.png`);
        }
    </script>
    <style>
        .bagde-visible {
            visibility: hidden;
        }

        .loader {
            z-index: 99;
        }

        .nav-no-display {
            display: none;
        }

    </style>
</head>


<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/IMG_2178_resize.png" height="70px" width="auto">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">
                        <i href="~/images/accounting.png"></i> ภาพรวมข้อมูล
                        </a>
                        </li>*@
                        <li class="nav-item" id="nav-hr">
                            <a class="nav-link" asp-area="" asp-controller="HR" asp-action="Index" onmouseover="onmouseoverAction('imgHR','hr-manager')" onmouseout="onmouseoutAction('imgHR','hr-manager')" id="navHR"><img id="imgHR" src="~/images/hr-manager.png" width="20px" /> <span id="spnHR"> ฝ่ายบุคคล</span></a>
                        </li>
                        <li class="nav-item" id="nav-sale">
                            <a class="nav-link" asp-area="" asp-controller="Sale" asp-action="Index" onmouseover="onmouseoverAction('imgSale','sales')" onmouseout="onmouseoutAction('imgSale','sales')" id="navSale"><img id="imgSale" src="~/images/sales.png" width="20px" /> <span id="spnSale"> การขาย</span></a>
                        </li>
                        <li class="nav-item" id="nav-3d">
                            <a class="nav-link" asp-area="" asp-controller="Design3D" asp-action="Index" onmouseover="onmouseoverAction('img3D','graphic-design')" onmouseout="onmouseoutAction('img3D','graphic-design')" id="navimg3D"><img id="img3D" src="~/images/graphic-design.png" width="20px" /> <span id="spn3D"> การออกแบบ 3D</span></a>
                        </li>
                        <li class="nav-item" id="nav-foreman">
                            <a class="nav-link" asp-area="" asp-controller="Foreman" asp-action="Index" onmouseover="onmouseoverAction('imgForeman','foreman')" onmouseout="onmouseoutAction('imgForeman','foreman')" id="navForeman"><img id="imgForeman" src="~/images/foreman.png" width="20px" /> <span id="spnForeman"> โฟร์แมน</span></a>
                        </li>
                        <li class="nav-item" id="nav-accounting">
                            <a class="nav-link" asp-area="" asp-controller="Accounting" asp-action="Index" onmouseover="onmouseoverAction('imgAccounting','accounting')" onmouseout="onmouseoutAction('imgAccounting','accounting')" id="navAccount"><img id="imgAccounting" src="~/images/accounting.png" width="20px" /> <span id="spnAccounting"> บัญชีและเอกสาร</span></a>
                        </li>
                        <li class="nav-item" id="nav-master">
                            <a class="nav-link" asp-area="" asp-controller="Master" asp-action="Index" onmouseover="onmouseoverAction('imgMaster','data-processing')" onmouseout="onmouseoutAction('imgMaster','data-processing')" id="navMaster"><img id="imgMaster" src="~/images/data-processing.png" width="20px" /> <span id="spnMaster"> ข้อมูลหลัก</span></a>
                        </li>
                        <li class="nav-item" id="nav-stores">
                            <a class="nav-link" asp-area="" asp-controller="Store" asp-action="Index" onmouseover="onmouseoverAction('imgStore','stores')" onmouseout="onmouseoutAction('imgStore','stores')"><img id="imgStore" src="~/images/stores.png" width="20px" /> <span id="spnStore"> สโตร์</span></a>
                        </li>
                        <li class="nav-item" id="nav-spec">
                            <a class="nav-link" asp-area="" asp-controller="Spec" asp-action="Index" onmouseover="onmouseoverAction('imgSpec','spec')" onmouseout="onmouseoutAction('imgSpec','spec')" id="navSpec"><img id="imgSpec" src="~/images/spec.png" width="20px" /> <span id="spnSpec"> การออกแบบ Spec</span></a>
                        </li>
                      
                        <li class="nav-item" id="nav-pd">
                            <a class="nav-link" asp-area="" asp-controller="ProductionDepartment" asp-action="Index" onmouseover="onmouseoverAction('imgHR','hr-manager')" onmouseout="onmouseoutAction('imgHR','hr-manager')" id="navPD"><img id="imgPD" src="~/images/hr-manager.png" width="20px" /> <span id="spnPD"> ฝ่ายผลิต</span></a>
                        </li>
                        <li class="nav-item" id="nav-td">
                            <a class="nav-link" asp-area="" asp-controller="Transportation" asp-action="Index" onmouseover="onmouseoverAction('imgHR','hr-manager')" onmouseout="onmouseoutAction('imgHR','hr-manager')" id="navTD"><img id="imgTD" src="~/images/hr-manager.png" width="20px" /> <span id="spnTD"> ฝ่ายขนส่ง</span></a>
                        </li>
                    </ul>

                </div>
                <div style="display:inline;float:right;">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" id="nav-approve">
                            @*<a href="/semicon/redline/index" class="commenticon" aria-expanded="false" title="click to view task" target="_blank" onclick="getmenuidbylink('/semicon/redline/index')"><i class="fa-solid fa-bell"></i><span class="badge badge-iconnoti" id="show_task_open">1</span></a>*@
                            <a class="nav-link" asp-area="" asp-controller="Approve" asp-action="Index">
                                <i class="fa fa-bell fa-lg"></i>
                                <span class="badge rounded-pill badge-notification bg-danger bagde-visible" id="spnApproveNumber"></span>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            @*<a href="/semicon/redline/index" class="commenticon" aria-expanded="false" title="click to view task" target="_blank" onclick="getmenuidbylink('/semicon/redline/index')"><i class="fa-solid fa-bell"></i><span class="badge badge-iconnoti" id="show_task_open">1</span></a>*@
                            <a href="" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><img src="~/images/girl.png" width="25px" /> <span id="spnloginName"></span></a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Login" asp-action="Index"><i class="fa fa-sign-out" aria-hidden="true"></i> ออกจากระบบ</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <script>
            $(function () {
                $('#spnloginName').html("");
                $('#spnloginName').html(localStorage.getItem('loginName'));

                callRoleNavMenu();
                callCountCustOrderWaitForApprove();

            });
        </script>
    </header>
    <div class="container-fluid">
        @*<main role="main" class="pb-3">*@
        @RenderBody()
        @*</main>*@
    </div>

    @*<footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2023 - MBDesignWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>